config/factories.yml:
  class:    \Axis\S1\ServiceContainer\Config\Handler\FactoryConfigHandler
  file:     %SF_PLUGINS_DIR%/AxisServiceContainerPlugin/lib/Axis/S1/ServiceContainer/Config/Handler/FactoryConfigHandler.php
  param:
    processors:
      include_file: \Axis\S1\ServiceContainer\Config\Processor\IncludeFile
      instantiate:
        class:  \Axis\S1\ServiceContainer\Config\Processor\Instantiate
        options:
          parameter_processors:
            - \Axis\S1\ServiceContainer\ParameterProcessor\RawValue
            - \Axis\S1\ServiceContainer\ParameterProcessor\DefinedService
            - \Axis\S1\ServiceContainer\ParameterProcessor\GetByTag
            - \Axis\S1\ServiceContainer\ParameterProcessor\sfConfigValue

      tag: \Axis\S1\ServiceContainer\Config\Processor\Tag
      initialization: \Axis\S1\ServiceContainer\Config\Processor\Initialization